version: '3.4'
services:

  wordpress:
    build: 
      context: ./wordpress
    profiles: ["wordpress"]
    ports:
      - "80:80"
    volumes:
      - wordpress-data:/app/wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: sample
    links:
      - db:db

  db:
    build:
      context: ./db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root

volumes:
  wordpress-data:
  db-data: