version: '3.4'
services:

  wordpress:
    build: 
      context: ./wordpress
    profiles: ["wordpress"]
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db-wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: sample
    restart: always
    
  drupal:
    build: 
      context: ./drupal
    profiles: ["drupal"]
    ports:
      - "80:80"
    environment:
      DRUPAL_DB_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: sample
    networks:
      - drupal-database
    restart: always

  db-drupal:
    build:
      context: ./db
    profiles: ["drupal"]
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-drupal-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
    networks:
      - drupal-database
    
  db-wordpress:
    build:
      context: ./db
    profiles: ["wordpress"]
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-wordpress-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root

networks:
  drupal-database:

volumes:
  db-drupal-data:
  db-wordpress-data: